# Generated by Django 5.2.8 on 2025-11-25 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_deliveryprofile_area_deliveryprofile_vehicle_number_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='deliveryprofile',
            name='area',
        ),
        migrations.RemoveField(
            model_name='deliveryprofile',
            name='vehicle_number',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='shop_name',
        ),
    ]
